version: '3.8'

services:
  first_app:
    container_name: first_app
    build:
      context: ./first_app
      dockerfile: Dockerfile
    entrypoint: sh -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    networks:
      - my_network
    ports:
      - "8000:8000"

  second_app:
    container_name: second_app
    build:
      context: ./second_app
      dockerfile: Dockerfile
    entrypoint: sh -c "uvicorn app:app --host 0.0.0.0 --port 5000"
    networks:
      - my_network
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - my_network

networks:
  my_network:
    name: my_network